utilities-database
loadTestProducts
	(Product
		name: 'Merrell Men''s Mother of All Boots'
		price: 1999.99
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00033.jpg')
		description:
			'Hike to your hearts content in this rugged, outdoor shoe.  The Mother of All Boots™ Ventilator Wide Width features performance suede leather & mesh uppers and an EVA midsole for stability and comfort.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00033.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00033.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00032.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00032.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00031.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00031.jpg');
		discount: 20 percent;
		save.
	(Product
		name: 'ECCO Men''s Vitrus'
		price: 4200
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00030.jpg')
		description:
			'Heads will turn when you step out in the Vitrus I Wing Tip Tie by ECCO.  This sophisticated style features ECCO calf crust leather and a molded inlay sole.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00030.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00030.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00029.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00029.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00028.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00028.jpg');
		save.
	(Product
		name: 'ECCO Men''s Vitrus - black'
		price: 4200
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00027.jpg')
		description:
			'Heads will turn when you step out in the Vitrus I Wing Tip Tie by ECCO.  This sophisticated style features ECCO calf crust leather and a molded inlay sole.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00027.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00027.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00026.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00026.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00025.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00025.jpg');
		discount: 30 percent;
		save.
	(Product
		name: 'Gore Slipper - Navy Knit'
		price: 1100
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00024.jpg')
		description:
			'Relax in the men''s Acorn Fave Gore Slipper this fall and winter.  Warm, Italian wool uppers and contoured TPR rubber cup soles will keep you feeling comfortable throughout your day.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00024.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00024.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00024.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00024.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00024.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00024.jpg');
		save.
	(Product
		name: 'Gore Slipper - Charcoal Tweed'
		price: 1100
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00023.jpg')
		description:
			'Relax in the men''s Acorn Fave Gore Slipper this fall and winter.  Warm, Italian wool uppers and contoured TPR rubber cup soles will keep you feeling comfortable throughout your day.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00023.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00023.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00023.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00023.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00023.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00023.jpg');
		discount: 20 percent;
		save.
	(Product
		name: 'Un.Nature Time - Black'
		price: 3299.99
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00022.jpg')
		description:
			'Walk it out in the sophisticated Un.Nature Time oxford by Clarks!  This casual style features a leather upper and sheepskin lining.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00022.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00022.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00021.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00021.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00020.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00020.jpg');
		discount: 20 percent;
		save.
	(Product
		name: 'Women''s Addington Chelsea Leather Boot - Tobacco'
		price: 3199.99
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00019.jpg')
		description:
			'Stylish comfort and waterproof uppers make the Sorel Addington Chelsea Leather Boot perfect for rainy Fall days and crisp Winter nights.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00019.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00019.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00018.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00018.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00017.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00017.jpg');
		save.
	(Product
		name: 'Women''s Addington Chelsea Leather Boot - Black'
		price: 3199.99
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00016.jpg')
		description:
			'Stylish comfort and waterproof uppers make the Sorel Addington Chelsea Leather Boot perfect for rainy Fall days and crisp Winter nights.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00016.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00016.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00015.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00015.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00014.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00014.jpg');
		save.
	(Product
		name: 'Women''s Laverne - Black'
		price: 2999.99
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00013.jpg')
		description:
			'The Beautifeel Laverne features exquisite comfort and a stunning pump silhouette that is perfect for the office';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00013.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00013.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00013.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00013.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00013.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00013.jpg');
		save.
	(Product
		name: 'Women''s Calla - Black'
		price: 2999.99
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00012.jpg')
		description: 'Turn heads in the office or out on the town when you''re wearing the Calla pump by Beautifeel.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00012.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00012.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00011.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00011.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00010.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00010.jpg');
		save.
	(Product
		name: 'Women''s Bootie Baqueira - Seaweed'
		price: 2899.99
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00009.jpg')
		description:
			'Fashionable leather laces, a mid-heel, and ample cushion combine to make the Pikolinos Bootie Baqueira perfect for daily wear.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00009.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00009.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00008.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00008.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00007.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00007.jpg');
		save.
	(Product
		name: 'Women''s Bootie Baqueira - Olmo'
		price: 2899.99
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00006.jpg')
		description:
			'Fashionable leather laces, a mid-heel, and ample cushion combine to make the Pikolinos Bootie Baqueira perfect for daily wear.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00006.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00006.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00005.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00005.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00004.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00004.jpg');
		save.
	(Product
		name: 'Women''s Bootie Baqueira - Arcilla'
		price: 2899.99
		imageUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00003.jpg')
		description:
			'Fashionable leather laces, a mid-heel, and ample cushion combine to make the Pikolinos Bootie Baqueira perfect for daily wear.';
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00003.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00003.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00002.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00002.jpg');
		addImage:
			(ProductImage
				url: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/700/product00001.jpg'
				thumbnailUrl: 'https://selfrefactoring.s3.amazonaws.com/shoestore/images/products/300/product00001.jpg');
		save